# Configuration File Of ItemInteract 
# aurthor MrNinja008
#  _____ _                  _____      _                      _   
# |_   _|                  |_   _|    | |                    | |  
#   | | |_ ___ _ __ ___      | | _ __ | |_ ___ _ __ __ _  ___| |_ 
#   | | __/ _ \ '_ ` _ \     | || '_ \| __/ _ \ '__/ _` |/ __| __|
#  _| |_| ||  __/ | | | | | _| || | | | ||  __/ | | (_| | (__| |_ 
#  \___/ \__\___|_| |_| |_| \___/_| |_|\__\___|_|  \__,_|\___|\__|

Item1: 312:9
Item1-Command: "bank"
Item1-Name: "Piggy Bank"

Item2: 312:10
Item2-Command: "shop"
Item2-Name: "EZ Market"

Item3: 276:0
Item3-Command: "heal"
Item3-Name: "Healing Root"

Item4: 283:0
Item4-Command: "teleport"
Item4-Name: "Time Machine"
